"""Generates the downloadable PDF report described in the PS doc."""
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)


def generate_risk_report_pdf(district_name: str, state: str, risk_score: float,
                              risk_level: str, confidence_score: float,
                              explanation: list, timestamp: datetime) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Title"], fontSize=20)
    elements = []

    elements.append(Paragraph("PrithviX — Landslide Risk Assessment Report", title_style))
    elements.append(Spacer(1, 0.5 * cm))
    elements.append(Paragraph(f"Location: {district_name}, {state}", styles["Normal"]))
    elements.append(Paragraph(f"Generated: {timestamp.strftime('%Y-%m-%d %H:%M UTC')}", styles["Normal"]))
    elements.append(Spacer(1, 0.8 * cm))

    level_colors = {
        "Safe": colors.green, "Moderate": colors.orange,
        "High": colors.orangered, "Critical": colors.red,
    }
    summary_data = [
        ["Risk Score", f"{risk_score:.1f}%"],
        ["Risk Level", risk_level],
        ["Confidence", f"{confidence_score:.1f}%"],
    ]
    summary_table = Table(summary_data, colWidths=[6 * cm, 6 * cm])
    summary_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
        ("TEXTCOLOR", (1, 1), (1, 1), level_colors.get(risk_level, colors.black)),
        ("FONTNAME", (1, 1), (1, 1), "Helvetica-Bold"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 0.8 * cm))

    elements.append(Paragraph("AI Explanation — Contributing Factors", styles["Heading2"]))
    exp_data = [["Factor", "Severity", "Detail"]]
    for item in explanation:
        exp_data.append([item["factor"], item["contribution"].title(), item["detail"]])
    exp_table = Table(exp_data, colWidths=[3.5 * cm, 2.5 * cm, 8 * cm])
    exp_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("PADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    elements.append(exp_table)
    elements.append(Spacer(1, 0.8 * cm))

    elements.append(Paragraph(
        "This report is generated by PrithviX, an AI-based early warning system for "
        "landslide risk monitoring in the North Eastern Region. Recommendations should "
        "be reviewed alongside on-ground assessment by disaster management authorities.",
        styles["Italic"],
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()
